### PR TITLE
Added Bitvavo ticker calls

### PR DESCRIPTION
**Pull request by cyberjunky**
Also added examples for Bitvavo ticker calls

### CODE REVIEW

**Comment by nardew** [comment]
Thanks @cyberjunky !

**Comment by cyberjunky** [comment]
@nardew no thanks, when is 3.8.1 being released to PyPi?

**Comment by nardew** [comment]
@cyberjunky 3.8.1 now available in PyPi

**Comment by cyberjunky** [comment]
@nardew great, it works!

**Pull request merged**
